spring:
  application:
    name: api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    initialization-mode: always
#    data: classpath:testdata.sql
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      # ddl-auto: update

server:
  address: 192.168.1.215
  port: 8081
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        security: DEBUG
        csrf:
          enabled: false
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      dmitr:
        api: TRACE

token:
  refresh:
    secret: ${JWT_REFRESH_KEY}
    lifetime: 14d
  access:
    secret: ${JWT_ACCESS_KEY}
    lifetime: 1m